FROM node:24 AS builder

WORKDIR /app

COPY . . 

RUN npm install

RUN npm run build

#---------------- Stage 2 STARTS -------------
FROM dhi.io/nginx:1.29-debian13 AS runner


COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080
