# Stage 1 (Builder stage) - USed to build the packages & app
FROM node:24 as builder

WORKDIR /app

COPY . . 

RUN npm install

RUN npm run build

# --------------- STAGE 1 COMPLETE -----------

# Stage 2 (Runner Stage) 
FROM node:24-alpine AS runner

WORKDIR /app

COPY package.json .

RUN npm install -g vite

COPY --from=builder /app/dist ./dist


CMD ["npm","run","preview", "--", "--host", "0.0.0.0", "--port", "4173"]
